### ISSUE TITLE
module keyboard doesnt exist

### ISSUE THREAD

**Issue by casuality3** [azh412/VirtualPianoBot#7]
when i run the script it says module not found "keyboard"

**Comment by azh412** [comment]
This might be because `pip` doesn't have it on your computer.
To fix this, execute `pip3 install keyboard` or `pip install keyboard`, depending on the python versions on your computer. More details [here](https://stackoverflow.com/questions/40832533/pip-or-pip3-to-install-packages-for-python-3#:~:text=When%20you%20install,the%20first%20installation.)

If you run into more issues, open another issue. I'll clarify the need to install keyboard in the README as well.
-azh
